/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  */

var f, i = 0, sum = 0;

do {
	f = fib( i++ );
    
	if ( f % 2 === 0 ) {
		sum += f;
	}
} while ( f < 4000000 );

console.log( sum );
 
function fib( n ) {
	if ( n === 1 || n === 0 ) {
		return n;
	}

	return fib( n - 1 ) + fib( n - 2 );
}
